[workspace]
members = ["crates/core", "crates/desktop"]
default-members = ["crates/desktop"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.99"
authors = ["Tremors"]
license = "GPL-3.0-only"
repository = "https://github.com/qtremors/tremors-music"

[workspace.dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = { version = "0.4", features = ["std"] }

[profile.release]
opt-level = "s"
lto = "thin"
codegen-units = 1
strip = "symbols"

[patch.crates-io]
gpui-pre-windows = { path = "third-party/gpui-pre-windows" }
